Repository yarsa/nepal-compliance, pull requests merged in 2025-07, with the labels that each got.

#107 add purchase return register report format as per IRD
  nepal_compliance/nepal_compliance/report/purchase_return_register_ird/__init__.py
  nepal_compliance/nepal_compliance/report/purchase_return_register_ird/download_ird_format.py
  nepal_compliance/nepal_compliance/report/purchase_return_register_ird/purchase_return_register_ird.js
  nepal_compliance/nepal_compliance/report/purchase_return_register_ird/purchase_return_register_ird.json
  nepal_compliance/nepal_compliance/report/purchase_return_register_ird/purchase_return_register_ird.py
Labels: large-pr

#109 add sales return register report format as per IRD
  nepal_compliance/nepal_compliance/report/sales_return_register_ird/__init__.py
  nepal_compliance/nepal_compliance/report/sales_return_register_ird/download_ird_format.py
  nepal_compliance/nepal_compliance/report/sales_return_register_ird/sales_return_register_ird.js
  nepal_compliance/nepal_compliance/report/sales_return_register_ird/sales_return_register_ird.json
  nepal_compliance/nepal_compliance/report/sales_return_register_ird/sales_return_register_ird.py
Labels: large-pr

#111 Merge changes from develop to master
  nepal_compliance/cbms_api.py
  nepal_compliance/custom_field.py
  nepal_compliance/email_utils.py
  nepal_compliance/fixtures/salary_component.json
  nepal_compliance/hooks.py
  nepal_compliance/nepal_compliance/print_format/invoice_nepal_compliance/__init__.py
  nepal_compliance/nepal_compliance/print_format/invoice_nepal_compliance/invoice_nepal_compliance.json
  nepal_compliance/nepal_compliance/print_format/invoice_nepal_compliance_copy/__init__.py
  nepal_compliance/nepal_compliance/print_format/invoice_nepal_compliance_copy/invoice_nepal_compliance_copy.json
  nepal_compliance/nepal_compliance/report/audit_log/audit_log.js
  nepal_compliance/nepal_compliance/report/audit_log/audit_log.py
  nepal_compliance/nepal_compliance/report/audit_trail/audit_trail.js
  nepal_compliance/nepal_compliance/report/audit_trail/audit_trail.py
  nepal_compliance/nepal_compliance/report/purchase_register_ird/__init__.py
  nepal_compliance/nepal_compliance/report/purchase_register_ird/download_ird_format.py
  nepal_compliance/nepal_compliance/report/purchase_register_ird/purchase_register_ird.js
  nepal_compliance/nepal_compliance/report/purchase_register_ird/purchase_register_ird.json
  nepal_compliance/nepal_compliance/report/purchase_register_ird/purchase_register_ird.py
  nepal_compliance/nepal_compliance/report/purchase_return_register_ird/__init__.py
  nepal_compliance/nepal_compliance/report/purchase_return_register_ird/download_ird_format.py
  nepal_compliance/nepal_compliance/report/purchase_return_register_ird/purchase_return_register_ird.js
  nepal_compliance/nepal_compliance/report/purchase_return_register_ird/purchase_return_register_ird.json
  nepal_compliance/nepal_compliance/report/purchase_return_register_ird/purchase_return_register_ird.py
  nepal_compliance/nepal_compliance/report/sales_register_ird/__init__.py
  nepal_compliance/nepal_compliance/report/sales_register_ird/download_ird_format.py
  nepal_compliance/nepal_compliance/report/sales_register_ird/sales_register_ird.js
  nepal_compliance/nepal_compliance/report/sales_register_ird/sales_register_ird.json
  nepal_compliance/nepal_compliance/report/sales_register_ird/sales_register_ird.py
  nepal_compliance/nepal_compliance/report/sales_return_register_ird/__init__.py
  nepal_compliance/nepal_compliance/report/sales_return_register_ird/download_ird_format.py
  nepal_compliance/nepal_compliance/report/sales_return_register_ird/sales_return_register_ird.js
  nepal_compliance/nepal_compliance/report/sales_return_register_ird/sales_return_register_ird.json
  nepal_compliance/nepal_compliance/report/sales_return_register_ird/sales_return_register_ird.py
  nepal_compliance/nepal_compliance/workspace/nepal_compliance/nepal_compliance.json
  nepal_compliance/patches.txt
  nepal_compliance/patches/__init__.py
  nepal_compliance/patches/add_custom_fields.py
  nepal_compliance/patches/payroll_entry.py
  nepal_compliance/patches/update_income_tax_components.py
  nepal_compliance/public/css/date.css
  nepal_compliance/public/js/bs_date.js
  nepal_compliance/public/js/utils.js
  nepal_compliance/public/js/validate.js
  nepal_compliance/utils.py
Labels: enhancement, maintenance, large-pr

#117 add missing custom fields to sales and purchase doctypes
  nepal_compliance/custom_field.py
  nepal_compliance/public/js/bs_date.js
Labels: maintenance

#119 (.env.example): defaults to VERSION_TAG=latest
  .env.example
Labels: maintenance

#121 add sales invoice increment in chronological order
  nepal_compliance/hooks.py
  nepal_compliance/nepal_compliance/print_format/invoice_nepal_compliance/invoice_nepal_compliance.json
  nepal_compliance/nepal_compliance/print_format/invoice_nepal_compliance_copy/invoice_nepal_compliance_copy.json
  nepal_compliance/utils.py
Labels: maintenance

#134 new status badges and a href link
  README.md
Labels: documentation
