Repository yarsa/nepal-compliance, pull requests merged in 2025-02, with the labels that each got.

#10 feat(audit log): add audit log report to track changes and updates
  README.md
  nepal_compliance/nepal_compliance/report/audit_log/__init__.py
  nepal_compliance/nepal_compliance/report/audit_log/audit_log.js
  nepal_compliance/nepal_compliance/report/audit_log/audit_log.json
  nepal_compliance/nepal_compliance/report/audit_log/audit_log.py
Labels: enhancement

#11 add discount and tds if it is include during transaction
  nepal_compliance/nepal_compliance/report/audit_log/audit_log.js
  nepal_compliance/nepal_compliance/report/audit_log/audit_log.py
  nepal_compliance/nepal_compliance/report/audit_trail/audit_trail.js
  nepal_compliance/nepal_compliance/report/audit_trail/audit_trail.py
  nepal_compliance/nepal_compliance/report/balance_confirmation/balance_confirmation.js
  nepal_compliance/nepal_compliance/report/balance_confirmation/balance_confirmation.py
  nepal_compliance/nepal_compliance/report/landing_cost_voucher/landing_cost_voucher.js
  nepal_compliance/nepal_compliance/report/landing_cost_voucher/landing_cost_voucher.py
  nepal_compliance/nepal_compliance/report/materialized_report/materialized_report.js
  nepal_compliance/nepal_compliance/report/materialized_report/materialized_report.py
  nepal_compliance/nepal_compliance/report/monthly_purchase_register/monthly_purchase_register.js
  nepal_compliance/nepal_compliance/report/monthly_purchase_register/monthly_purchase_register.py
  nepal_compliance/nepal_compliance/report/monthly_sales_register/monthly_sales_register.js
  nepal_compliance/nepal_compliance/report/monthly_sales_register/monthly_sales_register.py
  nepal_compliance/nepal_compliance/report/party_wise_purchase_register/party_wise_purchase_register.js
  nepal_compliance/nepal_compliance/report/party_wise_purchase_register/party_wise_purchase_register.py
  nepal_compliance/nepal_compliance/report/party_wise_sales_register/party_wise_sales_register.js
  nepal_compliance/nepal_compliance/report/party_wise_sales_register/party_wise_sales_register.py
  nepal_compliance/nepal_compliance/report/purchase_return_vat_register/purchase_return_vat_register.js
  nepal_compliance/nepal_compliance/report/purchase_return_vat_register/purchase_return_vat_register.py
  nepal_compliance/nepal_compliance/report/purchase_vat_register/purchase_vat_register.js
  nepal_compliance/nepal_compliance/report/purchase_vat_register/purchase_vat_register.py
  nepal_compliance/nepal_compliance/report/sales_cancellation_register/sales_cancellation_register.js
  nepal_compliance/nepal_compliance/report/sales_return_vat_register/sales_return_vat_register.js
  nepal_compliance/nepal_compliance/report/sales_return_vat_register/sales_return_vat_register.py
  nepal_compliance/nepal_compliance/report/sales_vat_register/sales_vat_register.js
  nepal_compliance/nepal_compliance/report/sales_vat_register/sales_vat_register.py
  nepal_compliance/nepal_compliance/report/vat_return_report/vat_return_report.js
  nepal_compliance/nepal_compliance/report/vat_return_report/vat_return_report.py
  nepal_compliance/public/js/bs_module.js
Labels: maintenance

#12 add paths-ignore to ignore .md files during docker build
  .github/workflows/docker-build-push.yml
Labels: enhancement

#16 adds supplier vat/pan detail to report
  nepal_compliance/nepal_compliance/report/purchase_return_vat_register/purchase_return_vat_register.py
  nepal_compliance/nepal_compliance/report/purchase_vat_register/purchase_vat_register.py
Labels: maintenance

#15 add supplier and customer vat/pan to purchase and sales doctype
  nepal_compliance/custom_field.py
Labels: maintenance

#17 ci(semgrep-rules.yml): adds Frappe Semgrep rules as linter CI config
  .github/workflows/semgrep-rules.yml
Labels: enhancement

#18 Update README.md; bagdes for docker pulls and frappe semgrep linter status
  README.md
Labels: documentation

#13 add discount and tds if it is included during sales transaction
  nepal_compliance/nepal_compliance/report/sales_return_vat_register/sales_return_vat_register.py
  nepal_compliance/nepal_compliance/report/sales_vat_register/sales_vat_register.js
  nepal_compliance/nepal_compliance/report/sales_vat_register/sales_vat_register.py
Labels: maintenance

#20 print format json: purchase invoice and sales invoice
  nepal_compliance/nepal_compliance/print_format/purchase_invoice_nepal_compliance/purchase_invoice_nepal_compliance.json
  nepal_compliance/nepal_compliance/print_format/sales_invoice_nepal_compliance/sales_invoice_nepal_compliance.json
Labels: bug, maintenance

#24 add filter by supplier, customer and include cancelled invoices in party wise sales and purchase register
  nepal_compliance/nepal_compliance/report/party_wise_purchase_register/party_wise_purchase_register.js
  nepal_compliance/nepal_compliance/report/party_wise_purchase_register/party_wise_purchase_register.py
  nepal_compliance/nepal_compliance/report/party_wise_sales_register/party_wise_sales_register.js
  nepal_compliance/nepal_compliance/report/party_wise_sales_register/party_wise_sales_register.py
Labels: enhancement, maintenance
