Repository yarsa/nepal-compliance, pull requests merged in 2025-05, with the labels that each got.

#57 enable BS date support by default when installing Nepal Compliance
  nepal_compliance/boot.py
  nepal_compliance/custom_code/payroll/salary_structure.py
  nepal_compliance/custom_field.py
  nepal_compliance/hooks.py
  nepal_compliance/install.py
  nepal_compliance/public/css/date.css
  nepal_compliance/public/js/bs_date.js
  nepal_compliance/public/js/formatter.js
  nepal_compliance/public/js/hrms_bs_date.js
  nepal_compliance/public/js/nepali_date.js
  nepal_compliance/public/js/payroll_bs_date.js
  nepal_compliance/public/js/salary_slip.js
Labels: enhancement, maintenance

#62 Develop to master merge fix
  nepal_compliance/boot.py
  nepal_compliance/custom_code/payroll/salary_structure.py
  nepal_compliance/custom_field.py
  nepal_compliance/hooks.py
  nepal_compliance/install.py
  nepal_compliance/nepal_compliance/report/landing_cost_voucher/landing_cost_voucher.py
  nepal_compliance/nepal_compliance/report/materialized_report/materialized_report.js
  nepal_compliance/nepal_compliance/report/materialized_report/materialized_report.py
  nepal_compliance/nepal_compliance/report/monthly_purchase_register/monthly_purchase_register.js
  nepal_compliance/nepal_compliance/report/monthly_purchase_register/monthly_purchase_register.py
  nepal_compliance/nepal_compliance/report/monthly_sales_register/monthly_sales_register.js
  nepal_compliance/nepal_compliance/report/monthly_sales_register/monthly_sales_register.py
  nepal_compliance/nepal_compliance/report/party_wise_purchase_register/party_wise_purchase_register.py
  nepal_compliance/nepal_compliance/report/party_wise_sales_register/party_wise_sales_register.py
  nepal_compliance/nepal_compliance/report/sales_cancellation_register/sales_cancellation_register.py
  nepal_compliance/nepal_compliance/report/vat_return_report/vat_return_report.js
  nepal_compliance/nepal_compliance/report/vat_return_report/vat_return_report.py
  nepal_compliance/public/css/date.css
  nepal_compliance/public/js/bs_date.js
  nepal_compliance/public/js/formatter.js
  nepal_compliance/public/js/hrms_bs_date.js
  nepal_compliance/public/js/nepali_date.js
  nepal_compliance/public/js/payroll_bs_date.js
  nepal_compliance/public/js/salary_slip.js
Labels: enhancement, maintenance, large-pr

#64 add one-click button for salary structure generation
  nepal_compliance/custom_code/payroll/salary_structure.py
  nepal_compliance/hooks.py
  nepal_compliance/public/js/custom_button.js
Labels: enhancement, maintenance

#66 merge changes from Develop to master
  nepal_compliance/custom_code/payroll/salary_structure.py
  nepal_compliance/hooks.py
  nepal_compliance/nepal_compliance/doctype/cbms_settings/cbms_settings.js
  nepal_compliance/nepal_compliance/doctype/cbms_settings/cbms_settings.json
  nepal_compliance/nepal_compliance/workspace/nepal_compliance/nepal_compliance.json
  nepal_compliance/public/icon/nepal-compliance.svg
  nepal_compliance/public/js/custom_button.js
  nepal_compliance/public/js/icon_patch.js
Labels: large-pr

#84 Revert "Merge fix"
  .github/workflows/docker-build-push.yml
  .github/workflows/semgrep-rules.yml
  commitlint.config.ts
  nepal_compliance/custom_code/payroll/salary_component.py
  nepal_compliance/nepal_compliance/report/audit_trail/audit_trail.js
  nepal_compliance/nepal_compliance/report/audit_trail/audit_trail.py
  nepal_compliance/nepal_compliance/report/landing_cost_voucher/landing_cost_voucher.js
  nepal_compliance/nepal_compliance/report/landing_cost_voucher/landing_cost_voucher.py
  nepal_compliance/nepal_compliance/report/materialized_report/materialized_report.py
  nepal_compliance/nepal_compliance/report/party_wise_purchase_register/party_wise_purchase_register.js
  nepal_compliance/nepal_compliance/report/party_wise_purchase_register/party_wise_purchase_register.py
  nepal_compliance/nepal_compliance/report/party_wise_sales_register/party_wise_sales_register.js
  nepal_compliance/nepal_compliance/report/party_wise_sales_register/party_wise_sales_register.py
  nepal_compliance/nepal_compliance/report/purchase_return_vat_register/purchase_return_vat_register.js
  nepal_compliance/nepal_compliance/report/purchase_return_vat_register/purchase_return_vat_register.py
  nepal_compliance/nepal_compliance/report/purchase_vat_register/purchase_vat_register.js
  nepal_compliance/nepal_compliance/report/purchase_vat_register/purchase_vat_register.py
  nepal_compliance/nepal_compliance/report/sales_cancellation_register/sales_cancellation_register.js
  nepal_compliance/nepal_compliance/report/sales_cancellation_register/sales_cancellation_register.py
  nepal_compliance/nepal_compliance/report/sales_return_vat_register/sales_return_vat_register.js
  nepal_compliance/nepal_compliance/report/sales_return_vat_register/sales_return_vat_register.py
  nepal_compliance/nepal_compliance/report/sales_vat_register/sales_vat_register.js
  nepal_compliance/nepal_compliance/report/sales_vat_register/sales_vat_register.py
  nepal_compliance/nepal_compliance/report/vat_return_report/vat_return_report.js
  nepal_compliance/nepal_compliance/report/vat_return_report/vat_return_report.py
  nepal_compliance/public/js/report_filter.js
  nepal_compliance/public/js/utils.js
Labels: large-pr

#86 Develop to master sync
  .github/workflows/docker-build-push.yml
  .github/workflows/semgrep-rules.yml
  commitlint.config.ts
  nepal_compliance/custom_code/payroll/salary_component.py
  nepal_compliance/nepal_compliance/report/audit_trail/audit_trail.js
  nepal_compliance/nepal_compliance/report/audit_trail/audit_trail.py
  nepal_compliance/nepal_compliance/report/landing_cost_voucher/landing_cost_voucher.js
  nepal_compliance/nepal_compliance/report/landing_cost_voucher/landing_cost_voucher.py
  nepal_compliance/nepal_compliance/report/materialized_report/materialized_report.py
  nepal_compliance/nepal_compliance/report/party_wise_purchase_register/party_wise_purchase_register.js
  nepal_compliance/nepal_compliance/report/party_wise_purchase_register/party_wise_purchase_register.py
  nepal_compliance/nepal_compliance/report/party_wise_sales_register/party_wise_sales_register.js
  nepal_compliance/nepal_compliance/report/party_wise_sales_register/party_wise_sales_register.py
  nepal_compliance/nepal_compliance/report/purchase_return_vat_register/purchase_return_vat_register.js
  nepal_compliance/nepal_compliance/report/purchase_return_vat_register/purchase_return_vat_register.py
  nepal_compliance/nepal_compliance/report/purchase_vat_register/purchase_vat_register.js
  nepal_compliance/nepal_compliance/report/purchase_vat_register/purchase_vat_register.py
  nepal_compliance/nepal_compliance/report/sales_cancellation_register/sales_cancellation_register.js
  nepal_compliance/nepal_compliance/report/sales_cancellation_register/sales_cancellation_register.py
  nepal_compliance/nepal_compliance/report/sales_return_vat_register/sales_return_vat_register.js
  nepal_compliance/nepal_compliance/report/sales_return_vat_register/sales_return_vat_register.py
  nepal_compliance/nepal_compliance/report/sales_vat_register/sales_vat_register.js
  nepal_compliance/nepal_compliance/report/sales_vat_register/sales_vat_register.py
  nepal_compliance/nepal_compliance/report/vat_return_report/vat_return_report.js
  nepal_compliance/nepal_compliance/report/vat_return_report/vat_return_report.py
  nepal_compliance/public/js/report_filter.js
  nepal_compliance/public/js/utils.js
Labels: large-pr
